import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AppSidebar } from "@/components/app-sidebar";
import { ClientesProvider } from "@/components/clientes/clientes-provider";
import { ComprasProvider } from "@/components/compras/compras-provider";
import { PagosProvider } from "@/components/pagos/pagos-provider";
import { VentasProvider } from "@/components/ventas/ventas-provider";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SidebarProvider>
          <ClientesProvider>
            <VentasProvider>
              <ComprasProvider>
                <PagosProvider>
                  <AppSidebar />
                  <SidebarInset>
                    <header className="flex h-12 shrink-0 items-center gap-2 border-b px-4">
                      <SidebarTrigger />
                    </header>
                    {children}
                  </SidebarInset>
                </PagosProvider>
              </ComprasProvider>
            </VentasProvider>
          </ClientesProvider>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
